### ISSUE TITLE
polymorphic embed doesnt run embed`s changeset

### ISSUE THREAD

**Issue by BlueHotDog** [mathieuprog/polymorphic_embed#28] opened 2020-12-23 17:51 UTC
given the following embed:
```elixir
defmodule Embedded do
  @moduledoc false
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key false
  embedded_schema do
    field :x, :string
  end

  def changeset(embedded, params) do
    embedded
    |> cast(params, [:x])
    |> validate_required([:x])
  end
end
```

And the following usage:
```elixir
defmodule Parent do
  @moduledoc false
  use Ecto.Schema
  import PolymorphicEmbed, only: [cast_polymorphic_embed: 2]


  schema "patches" do
    field :data, PolymorphicEmbed, types: [
      embedded: Embedded
    ]
    timestamps()
  end


  @doc false
  def create_changeset(%Patch{} = patch) do
    patch
    |> cast(%{}, [])
    |> cast_polymorphic_embed(:data)
    |> validate_required([:data])
  end
end
```

I was expecting the changeset to run, but they're not. (checked via tests, by removing x attribute expecting things to fail, also the coveralls says it's never run)

**Comment by mathieuprog** [comment] 2020-12-23 18:53
Will look into it 🎅

**Comment by mathieuprog** [comment] 2020-12-23 23:08
Can you set the `:on_type_not_found` option to `:raise` and check if you have an error?
I think the only way the changeset wouldn't run is that it cannot find the type (to pick the right embed).

Note also that I made a new release (1.0.0), and there is a breaking change, you have to set a new mandatory option `:on_replace` to `:update`.

**Comment by BlueHotDog** [comment] 2020-12-24 10:25
Just tried, updated to v1, added the on_replace + on_type_not_found. still same issue

**Comment by mathieuprog** [comment] 2020-12-24 10:53
We have tests that for example check for validation error messages. Without running the embed's `changeset` function that wouldn't be possible.
Also since v1 there is no more way to cast an embed without having a changeset.

I would recommend you to inspect the changeset. As a last resort add some IO.inspect into the libary code and run `mix deps.compile` to see where the error lies.

The embed's changeset is called here:
https://github.com/mathieuprog/polymorphic_embed/blob/v1.0.0/lib/polymorphic_embed.ex#L71
I would add inspects to check in which branch the code goes, run `mix deps.compile`, and we'll have an answer.

Let me know

**Comment by BlueHotDog** [comment] 2020-12-24 10:55
Ok, i think i found it.
I was expecting i could just pass the %Embedded{} module as a :data to Parent.
But seems like i need to specifically specify a __type__ and take the struct and convert it to a map.

I think this part is actually just missing in the documentation

**Comment by mathieuprog** [comment] 2020-12-24 11:16
Actually that should work. We know for example `Embedded` is of which type.

But you mentioned that you expect the `changeset` function to run. That means that you send in params for that field? In that case you need indeed the `__type__`.

It's a bit confusing sorry.
But you can check this test: https://github.com/mathieuprog/polymorphic_embed/blob/v1.0.0/test/polymorphic_embed_test.exs#L95

Structs can be stored without `__type__` field.

**Comment by BlueHotDog** [comment] 2020-12-24 12:09
Ok, managed to proceed, but now stuck on another weird error:
```
  ** (FunctionClauseError) no function clause matching in PolymorphicEmbed.dump/3

     The following arguments were given to PolymorphicEmbed.dump/3:

         # 1
         %{__type__: :embedded, x: "3"}

         # 2
         #Function<31.132136930/2 in Ecto.Type.process_dumpers/3>

         # 3
         %{metadata: [%{identify_by_fields: [], module: Embedded, type: "embedded"}], on_type_not_found: :raise}

     Attempted function clauses (showing 3 out of 3):

         def dump(%Ecto.Changeset{valid?: false}, _dumper, _params)
         def dump(%_module{} = struct, dumper, %{metadata: metadata})
         def dump(nil, dumper, _params)
```

**Comment by mathieuprog** [comment] 2020-12-24 12:33
That's interesting. I would like to add this as a test case in the project. As soon as I can reproduce it, it will be fixed.
Is your code shareable somehow?

If not, I need more info as to how that error got raised.

**Comment by BlueHotDog** [comment] 2020-12-24 12:37
Happy to jump and show you the code right now, I'm on the Elixir Discord BlueHotDog#5021

**Comment by mathieuprog** [comment] 2020-12-24 14:00
Troubleshoot'ed through Discord.

**Closed by mathieuprog** 2020-12-24 14:00 UTC
